private_computation:
  dependency:
    PrivateComputationInstanceRepository:
      class: fbpcs.private_computation.repository.private_computation_instance_local.LocalPrivateComputationInstanceRepository
      constructor:
        base_dir: /fbpcs_instances
    ContainerService:
      class: fbpcp.service.container_aws.AWSContainerService
      constructor:
        # AWS region - ex. us-west-2
        region: TODO
        # ECS cluster name - ex. pl-cluster-private-attribution-partner
        cluster: TODO
        # AWS subnet IDs - ex. [subnet-123456789abcdefgh, subnet-987654321abcdefgh]
        subnets: [TODO]
        # AWS access key
        access_key_id: TODO
        # AWS access secret
        access_key_data: TODO
        # AWS session token
        # session_token: TODO
    StorageService:
      class: fbpcp.service.storage_s3.S3StorageService
      constructor:
        # AWS region - ex. us-west-2
        region: TODO
        # AWS access key
        access_key_id: TODO
        # AWS access secret
        access_key_data: TODO
        # AWS session token
        # session_token: TODO
    ValidationConfig:
      is_validating: false
      synthetic_shard_path:
    OneDockerBinaryConfig:
      default:
        constructor:
          tmp_directory: /tmp
          binary_version: latest
    OneDockerServiceConfig:
      constructor:
        # TODO: Change this value with pl-task task definition in the following format (see Container Definitions section inside selected task definition revision):
        # <task definition name>:<revision>#<container name>
        # ex. pl-task-private-attribution-partner:1#pl-container-private-attribution-partner
        task_definition: TODO_ONEDOCKER_TASK_DEFINITION
    PCValidatorConfig:
      class: fbpcs.private_computation.entity.pc_validator_config.PCValidatorConfig
      constructor:
        ### AWS region - ex. us-west-2
        region: TODO
        ### Toggle running the PCPreValidator
        # pc_pre_validator_enabled: false
pid:
  dependency:
mpc:
  dependency:
    MPCGameService:
      class: fbpcs.private_computation.service.mpc.mpc_game.MPCGameService
      dependency:
        PrivateComputationGameRepository:
          class: fbpcs.private_computation.repository.private_computation_game.PrivateComputationGameRepository
    MPCInstanceRepository:
      class: fbpcs.common.repository.mpc_instance_local.LocalMPCInstanceRepository
      constructor:
        base_dir: /fbpcs_instances
graphapi:
  access_token: TODO
