/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#pragma once

#include <filesystem>
#include <istream>
#include <ostream>
#include <unordered_map>
#include <vector>

namespace pid::combiner {
/*
This library implements the idSwapMultiKey that is used to swap the sensitive id
in a data file with the private id generated by the pid service
*/
void idSwapMultiKey(
    std::istream& dataInFilePath,
    std::istream& spineIdFilePath,
    std::ostream& outFilePath,
    std::int32_t max_id_column_cnt);
} // namespace pid::combiner
