/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#pragma once
#include <folly/logging/xlog.h>
#include <filesystem>
#include <fstream>
#include <ostream>
#include <string>
#include <vector>

#include "fbpcf/io/api/BufferedReader.h"
#include "fbpcf/io/api/FileIOWrappers.h"
#include "fbpcs/data_processing/id_combiner/AddPaddingToCols.h"
#include "fbpcs/data_processing/id_combiner/DataPreparationHelpers.h"
#include "fbpcs/data_processing/lift_id_combiner/LiftIdSpineCombinerOptions.h"
#include "fbpcs/data_processing/lift_id_combiner/LiftStrategy.h"

namespace pid::combiner {
struct FileMetaData {
  std::string headerLine;
  bool isPublisherDataset;
};
/*
LiftStrategy is an base class which has process functions for lift ID
combiner.
*/
class LiftStrategy {
 public:
  const std::vector<std::string> requiredPublisherCols = {
      "opportunity_timestamp",
      "test_flag"};
  const std::vector<std::string> requiredPartnerCols = {"event_timestamp"};
  /**
   * getFileType() will return the type of file. Publisher or Partner
   * If the file format is wrong, rasise the excption
   *
   * @param headerLine the file header
   * @return the file type. If the file type is publisher, return true.
   *Otherwise return false.
   **/
  virtual bool getFileType(std::string headerLine);
  /**
   * aggregate() will aggreagte the file if the pid is the same.
   *
   * @param idSwapOutFile the file from the idSwap() which has the pid colums
   * @param isPublisherDataset file type. True is Publisher, false is partner
   * @param outputPath the file path that stores aggreaged result
   * @param tmpDirectory the temp directory to create tmp file to store the
   *stringstram
   * @param sortStrategy sortStrategy to sort records
   * @return idSwapOutFile output stream of private-id file
   **/
  virtual void aggregate(
      std::stringstream& idSwapOutFile,
      bool isPublisherDataset,
      std::string outputPath,
      std::string tmpDirectory,
      std::string sortStrategy);
  /**
   * processHeader() will extract the header of the file, check the tpye of the
   * file and get meta data
   *
   * @param file data file generated by the ID_MATCHING stage
   * @return FileMetaData: header line, file type and aggregated columns
   **/
  virtual FileMetaData processHeader(
      const std::shared_ptr<fbpcf::io::BufferedReader>& file);
  virtual ~LiftStrategy() {}
  /**
   * run() will execute different steps according to differnt id_combiner
   **/
  virtual void run() = 0;
};

} // namespace pid::combiner
