#!/usr/bin/env python3
# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# pyre-strict


import os
import pathlib
import stat

from fbpcs.private_computation.entity.private_computation_status import (
    PrivateComputationInstanceStatus,
)


OUTPUT_DIR: pathlib.Path = (
    pathlib.Path(__file__).parent / "test_resources" / "status_names"
)
STATUS_NAME_SUFFIX: str = ".txt"
PREAMBLE: str = """# NOTE: This file was originally autogenerated by a script.
# If you find yourself needing to edit it, something has probably gone very
# wrong. Status names should be considered immutable forever. If we ever try to
# rename or delete a status, it can put old instances on the advertiser's side
# into a permanently unrecoverable state. Please proceed with extreme caution.

"""


def gen_status_files(output_dir: pathlib.Path) -> None:
    for status in PrivateComputationInstanceStatus:
        filename = f"{status.value.lower()}{STATUS_NAME_SUFFIX}"
        path = output_dir / filename
        if not os.path.exists(path):
            with open(path, "w") as f:
                print(PREAMBLE, file=f)
                print(status.value, file=f)
            # Mark the file as read-only
            os.chmod(path, stat.S_IRUSR | stat.S_IRGRP | stat.S_IROTH)


if __name__ == "__main__":
    gen_status_files(OUTPUT_DIR)
