name: Build and Publish the Production OneDocker Image

on:
  push:
    branches:
      - 'main'
    paths:
      - 'docker/onedocker/prod/**'
  workflow_dispatch:


env:
  REGISTRY: ghcr.io
  GH_REGISTRY_IMAGE_NAME: ghcr.io/${{ github.repository }}/prod/onedocker

jobs:
  build_and_publish_image:
    name: Build Image
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-onedocker-prod-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-onedocker-prod

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        uses: docker/build-push-action@v3
        with:
          context: docker/onedocker/prod
          file: docker/onedocker/prod/Dockerfile.ubuntu
          tags: |
            ${{ env.GH_REGISTRY_IMAGE_NAME }}:${{ github.sha }}
            ${{ env.GH_REGISTRY_IMAGE_NAME }}:latest
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      # This ugly bit is necessary or else our cache will grow forever
      # until it hits GitHub's limit of 5GB.
      # Temp fix: T135482742
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
