name: Build and Publish EMP Games Image

on:
  workflow_call:
    inputs:
      tag:
        description: The docker tag to publish with
        required: true
        default: latest
        type: string
      fbpcf_version:
        description: The FBPCF version to build with
        required: true
        default: latest
        type: string

env:
  DISTRO: ubuntu
  REGISTRY: ghcr.io
  RC_REGISTRY_IMAGE_NAME: ghcr.io/${{ github.repository }}/rc/emp_games

jobs:
  build_emp_games_image:
    name: Build EMP Games Image
    runs-on: [self-hosted, fbpcs-build]
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-emp-games-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-emp-games

      - name: Pull FBPCF Image
        run: docker pull ghcr.io/facebookresearch/fbpcf/ubuntu:${{ inputs.fbpcf_version }}

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Publish EMP Games image to GHCR
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/emp_games/Dockerfile.ubuntu
          tags: |
            ${{ env.RC_REGISTRY_IMAGE_NAME }}:latest
            ${{ env.RC_REGISTRY_IMAGE_NAME }}:${{ github.sha }}
          build-args: |
            tag=latest
            os_release=20.04
            fbpcf_image=ghcr.io/facebookresearch/fbpcf/ubuntu:${{ inputs.fbpcf_version }}
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      # This ugly bit is necessary or else our cache will grow forever
      # until it hits GitHub's limit of 5GB.
      # Temp fix: T135482742
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
