name: Build and Publish Binary Image

on:
  workflow_call:
    inputs:
      image_to_build:
        description: Which image we should build. Can be either emp_games or data_processing
        required: true
        type: string
      tag:
        description: The docker tag to publish with
        required: true
        default: latest
        type: string
      fbpcf_version:
        description: The FBPCF version to build with
        required: true
        default: latest
        type: string
      load_image_locally:
        description: A boolean on whether we should load the image locally or not.
        required: false
        default: false
        type: boolean
      push_to_registry:
        description: A boolean on whether we should push the image to the RC registry or not.
        required: false
        default: false
        type: boolean

env:
  DISTRO: ubuntu
  REGISTRY: ghcr.io
  RC_REGISTRY_URL: ghcr.io/${{ github.repository }}/rc/

jobs:
  build_image:
    name: Build Image
    runs-on: [self-hosted, fbpcs-build]
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Get Docker Image Name
        id: get_docker_image_name
        run: |
          echo "image_tag_name=$(echo ${{ inputs.image_to_build }} | tr '_' '-')" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Pull FBPCF Image
        run: docker pull ghcr.io/facebookresearch/fbpcf/ubuntu:${{ inputs.fbpcf_version }}

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/${{ inputs.image_to_build }}/Dockerfile.ubuntu
          tags: |
            ${{ env.RC_REGISTRY_URL }}${{ steps.get_docker_image_name.outputs.image_tag_name }}:${{ github.sha }}
          build-args: |
            tag=latest
            os_release=20.04
            fbpcf_image=ghcr.io/facebookresearch/fbpcf/ubuntu:${{ inputs.fbpcf_version }}
          push: ${{ inputs.push_to_registry }}
          load: ${{ inputs.load_image_locally }}
          cache-from: type=gha,scope=${{ steps.get_docker_image_name.outputs.image_tag_name }}-${{ github.ref_name }}
          cache-to: type=gha,scope=${{ steps.get_docker_image_name.outputs.image_tag_name }}-${{ github.ref_name }},mode=max
