name: End to End Tests on RC
run-name: End to End test on RC

on:
  schedule:
    - cron: '0 16-22/2 * * 1-5' # Every 2 hours from 16:00 - 22:00 UTC (8-2 PST and 9-3 PDT) M-F
  workflow_dispatch:


jobs:
  pl_test:
    name: PL E2E Test
    uses: ./.github/workflows/one_command_runner_test.yml
    with:
      study_id: '322561936733136'
      input_path: "https://fbpcs-github-e2e.s3.us-west-2.amazonaws.com/lift/inputs/partner_e2e_input.csv"
      expected_result_path: "https://fbpcs-github-e2e.s3.us-west-2.amazonaws.com/lift/results/partner_expected_result_pcf2.json"
      build_id: cron
      test_name: PL E2E Tests
      test_config: config_pl_test.yml
    secrets: inherit # pass all secrets

  pl_test:
    name: UDP PL E2E Test
    uses: ./.github/workflows/one_command_runner_test.yml
    with:
      study_id: '44902210680731'
      input_path: "https://fbpcs-github-e2e-runner.s3.us-west-1.amazonaws.com/lift/inputs/partner_e2e_input.csv"
      expected_result_path: "https://fbpcs-github-e2e-runner.s3.us-west-1.amazonaws.com/lift/results/partner_expected_result_pcf2.json"
      build_id: cron
      test_name: UDP Tests
      test_config: rc_udp_pl_test.yml
    secrets: inherit # pass all secrets

  mk_pl_test:
    name: Multi-Key PL E2E Test
    uses: ./.github/workflows/one_command_runner_test.yml
    with:
      study_id: '38402205691678'
      input_path: https://fbpcs-github-e2e.s3.us-west-2.amazonaws.com/lift/inputs/partner_e2e_multikey_input.csv
      expected_result_path: https://fbpcs-github-e2e.s3.us-west-2.amazonaws.com/lift/results/partner_expected_result_multikey.json
      build_id: cron
      test_name: Multi-key PL E2E Tests
    secrets: inherit # pass all secrets

  pa_test:
    name: PA Test Run
    uses: ./.github/workflows/pa_one_command_runner_test.yml
    with:
      dataset_id: '1127612294482487'
      build_id: cron
      test_name: PA E2E Tests
    secrets: inherit # pass all secrets

  mk_pa_test:
    name: Multi Key PA Test Run
    uses: ./.github/workflows/pa_one_command_runner_test.yml
    with:
      dataset_id: '3204590196477122'
      input_path: https://fbpcs-github-e2e.s3.us-west-2.amazonaws.com/attribution/inputs/partner_e2e_multikey_input.csv
      expected_result_path: https://fbpcs-github-e2e.s3.us-west-2.amazonaws.com/attribution/results/partner_expected_result_last_click_multikey.json
      build_id: cron
      test_name: Multi-key PA E2E Tests
    secrets: inherit # pass all secrets
