name: End To End Test

on:
  workflow_dispatch:
    inputs:
      lift_study_id:
        description: Lift study id
        required: true
        default: 32102205110410
      lift_objective_id:
        description: Lift objective id
        required: true
        default: 40202203600681
      lift_input_path:
        description: S3 path to synthetic data
        required: true
        default: https://fbpcs-github-e2e.s3.us-west-2.amazonaws.com/lift/inputs/partner_e2e_input.csv
      lift_expected_result_path:
        description: S3 path to expected results from synthetic run
        required: true
        default: https://fbpcs-github-e2e.s3.us-west-2.amazonaws.com/lift/results/partner_expected_result.json
      multi_key_lift_study_id:
        description: Lift study id
        required: true
        default: 38402205691678
      multi_key_lift_objective_id:
        description: Lift objective id
        required: true
        default: 43702205627286
      multi_key_lift_input_path:
        description: S3 path to synthetic data
        required: true
        default: https://fbpcs-github-e2e.s3.us-west-2.amazonaws.com/lift/inputs/partner_e2e_input.csv
      multi_key_lift_expected_result_path:
        description: S3 path to expected results from synthetic run
        required: true
        default: https://fbpcs-github-e2e.s3.us-west-2.amazonaws.com/lift/results/partner_expected_result.json
      attribution_dataset_id:
        description: Attribution Dataset id
        required: true
        default: 1127612294482487
      attribution_input_path:
        description: S3 path to synthetic attribution data
        required: true
        default: https://fbpcs-github-e2e.s3.us-west-2.amazonaws.com/attribution/inputs/partner_e2e_input.csv
      attribution_expected_result_path:
        description: S3 path to expected results from synthetic run
        required: true
        default: https://fbpcs-github-e2e.s3.us-west-2.amazonaws.com/attribution/results/partner_expected_result_last_click.json
      multi_key_attribution_dataset_id:
        description: Attribution Dataset id
        required: true
        default: 3204590196477122
      multi_key_attribution_input_path:
        description: S3 path to synthetic attribution data
        required: true
        default: https://fbpcs-github-e2e.s3.us-west-2.amazonaws.com/attribution/inputs/partner_e2e_input.csv
      multi_key_attribution_expected_result_path:
        description: S3 path to expected results from synthetic run
        required: true
        default: https://fbpcs-github-e2e.s3.us-west-2.amazonaws.com/attribution/results/partner_expected_result_last_click.json
      tag:
        description: Version tag to use
        required: true
        default: rc
      tracker_hash:
        description: '[Internal usage] Used for tracking workflow job status within Meta infra'
        required: false
        type: str

env:
  FBPCS_CONTAINER_REPO_URL: ghcr.io/facebookresearch/fbpcs
  FBPCS_IMAGE_NAME: coordinator
  FBPCS_GRAPH_API_TOKEN: ${{ secrets.FBPCS_GRAPH_API_TOKEN }}
  CONSOLE_OUTPUT_FILE: /tmp/output.txt

jobs:
  lift_test:
    name: Private Lift E2E test
    steps:
      - name: Private Lift E2E test
        uses: ./.github/workflows/e2e_tests/one_command_runner_test.yml
  attribution_test:
    name: Private Attribution E2E test
    steps:
      - name: Private Attribution E2E test
        uses: ./.github/workflows/e2e_tests/pa_one_command_runner_test.yml
  multi_key_lift_test:
    name: Multi Key Private Lift E2E test
    steps:
      - name: Multi Key Private Lift E2E test
        uses: ./.github/workflows/e2e_tests/one_command_runner_test.yml
        with:
          lift_study_id: ${{ github.event.inputs.multi_key_lift_study_id }}
          lift_objective_id: ${{ github.event.inputs.multi_key_lift_objective_id }}
          lift_input_path: ${{ github.event.inputs.multi_key_lift_input_path }}
          lift_expected_result_path: ${{ github.event.inputs.multi_key_lift_expected_result_path }}
          tag: ${{ github.event.inputs.tag }}
          tracker_hash: ${{ github.event.inputs.tracker_hash }}
  multi_key_attribution_test:
    name: Multi Key Private Attribution E2E test
    steps:
      - name: Multi Key Private Attribution E2E test
        uses: ./.github/workflows/e2e_tests/pa_one_command_runner_test.yml
        with:
          attribution_dataset_id: ${{ github.event.inputs.multi_key_attribution_dataset_id }}
          attribution_input_path: ${{ github.event.inputs.multi_key_attribution_input_path }}
          attribution_expected_result_path: ${{ github.event.inputs.multi_key_attribution_expected_result_path }}
          tag: ${{ github.event.inputs.tag }}
          tracker_hash: ${{ github.event.inputs.tracker_hash }}
