name: Private Lift E2E tests
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Manually running PL E2E tests'
        default: 'Run'

env:
  DISTRO: ubuntu
  REGISTRY: ghcr.io
  CONTAINER_NAME: e2e_pl_container
  COORDINATOR_IMAGE: ghcr.io/facebookresearch/fbpcs/coordinator:latest

jobs:
  run:
   runs-on: self-hosted
   name: Running Private Lift E2E Tests
   permissions:
    contents: read
    packages: write

   steps:
     - uses: actions/checkout@v2

     - name: Log into registry ${{ env.REGISTRY }}
       uses: docker/login-action@v1
       with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

     - name: Pull coordinator image
       run: |
        docker pull ${{ env.COORDINATOR_IMAGE }}

     - name: Start container
       run: |
        ./start_container.sh ${{ env.CONTAINER_NAME }} ${{ env.COORDINATOR_IMAGE }}
       working-directory: ./fbpcs/tests/github/

     - name: Lift - Create Instance
       run: |
        ./lift_run_stages.sh ${{ env.CONTAINER_NAME }} create_instance
       working-directory: ./fbpcs/tests/github/

     - name: Lift - Id Match
       run: |
        ./lift_run_stages.sh ${{ env.CONTAINER_NAME }} id_match
       working-directory: ./fbpcs/tests/github/

     - name: Check Status
       timeout-minutes: 5
       run: |
        ./check_status.sh ${{ env.CONTAINER_NAME }} lift
       working-directory: ./fbpcs/tests/github/

     - name: Lift - Prepare Compute Input
       run: |
        ./lift_run_stages.sh ${{ env.CONTAINER_NAME }} prepare_compute_input
       working-directory: ./fbpcs/tests/github/

     - name: Check Status
       timeout-minutes: 5
       run: |
        ./check_status.sh ${{ env.CONTAINER_NAME }} lift
       working-directory: ./fbpcs/tests/github/

     - name: Lift - Compute Metrics
       run: |
        ./lift_run_stages.sh ${{ env.CONTAINER_NAME }} compute_metrics
       working-directory: ./fbpcs/tests/github/

     - name: Check Status
       timeout-minutes: 5
       run: |
        ./check_status.sh ${{ env.CONTAINER_NAME }} lift
       working-directory: ./fbpcs/tests/github/

     - name: Lift - Aggregate Shards
       run: |
        ./lift_run_stages.sh ${{ env.CONTAINER_NAME }} aggregate_shards
       working-directory: ./fbpcs/tests/github/

     - name: Check Status
       timeout-minutes: 5
       run: |
        ./check_status.sh ${{ env.CONTAINER_NAME }} lift
       working-directory: ./fbpcs/tests/github/

     - name: Lift - Validate Results
       run: |
        ./validate_result.sh lift
       working-directory: ./fbpcs/tests/github/

     - name: Cleanup
       run: |
        docker stop ${{ env.CONTAINER_NAME }}
        docker rm ${{ env.CONTAINER_NAME }}
