name: Tag Bundle Commit

on:
  workflow_dispatch:
    inputs:
      bundle_id:
        description: "The bundle id to tag the commit on main with"
        required: true
        type: string
      tracker_hash:
        description: "[Internal usage] Used for tracking workflow job status within Meta infra"
        required: false
        type: string

jobs:
  tag_main:
    runs-on: ubuntu-latest
    name: Tag main with bundle id

    steps:
      - name: Print Tracker Hash
        run: echo ${{ inputs.tracker_hash }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Add tag to commit
        id: tag_version
        run: |
          git tag ${{ inputs.bundle_id }}
          git push origin ${{ inputs.bundle_id }}
