name: Test building image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  building_image:
    runs-on: 16-core

    steps:
    - uses: actions/checkout@v2

    - name: Build image
      run: |
        ./build-docker.sh onedocker
