name: Test building image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  building_image:
    runs-on: self-hosted

    steps:
    - name: Test
      run: |
        echo "Test"
